
name: Sync Submodules

on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update sub modules
        run: |
          git submodule update --remote
          TAG=`cd lima && git describe --tags $(git rev-list --tags --max-count=1)`
          echo "Pulling changes from release: $TAG"
          cd lima && git checkout v0.14.0
          
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: bump submodules
          signoff: true
          title: 'build(deps): Bump submodules'
