# Trigger a workflow on tag

name: Publish release to s3

# Controls when the workflow will run
on:
  workflow_dispatch
  
jobs:
  upload-please:
    runs-on: ubuntu-latest
    steps:
      - name: Download last release
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "vsiravar/github-actions-experiments"
          latest: true
          tarBall: true
          zipBall: true
      - name: update dependencies url
        run: |
          ls -lrth
            
